ucsc_genome_browser_setup_script: https://raw.githubusercontent.com/ucscGenomeBrowser/kent/fdded708bc8405da6d0ff43d42f0092a872a0a97/src/product/installer/browserSetup.sh
ucsc_genome_browser_setup_script_checksum: sha256:e47cd21c479a53d3157a4cd54f867dc26420d5f825d0b6954257e3ee3054882d

ucsc_genome_browser_setting_GBDBDIR: "/srv/ucsc_genome_browser/gbdb/"

ucsc_genome_browser_assemblies: []
ucsc_genome_browser_assemblies_env: "OS=linux MACH=x86_64"
