# Tests block "Work around `GBDBDIR` setting being ignored by the installation script"
---
- name: Ensure UCSC Genome Browser is installed
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Check if UCSC Genome Browser is already installed
      block:
        - name: Stat UCSC Genome Browser installation flag
          ansible.builtin.stat:
            path: "/usr/local/apache/cgiInstallComplete.flag"
          register: ucsc_genome_browser_installation_flag

        - name: Assert UCSC Genome Browser installation flag exists
          ansible.builtin.assert:
            that: ucsc_genome_browser_installation_flag.stat.exists
            fail_msg: "UCSC Genome Browser installation flag not found. Installation may have failed."

    - name: Ensure `/gbdb/` is a symlink to the correct location
      block:
        - name: Stat `/gbdb/` symlink
          ansible.builtin.stat:
            path: /gbdb
          register: gbdb_symlink_stat

        - name: Assert that `/gbdb/` is a symlink and points the correct location
          ansible.builtin.assert:
            that:
              - gbdb_symlink_stat.stat.exists
              - gbdb_symlink_stat.stat.islnk
              - gbdb_symlink_stat.stat.lnk_source == "/srv/ucsc_genome_browser/gbdb"
            fail_msg: "`/gbdb/` is not a symlink pointing to the correct location. It should point to `{{ ucsc_genome_browser_setting_GBDBDIR }}`."
