---
- name: Apply UCSC Genome Browser hg.conf settings
  community.general.ini_file:
    path: "{{ ucsc_genome_browser_setting_CGIBINDIR }}/hg.conf"
    section: null  # hg.conf is a flat key=value file with no sections
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    state: present
  loop: "{{ ucsc_genome_browser_hg_conf_settings | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
