name: Ansible Molecule

on:
  workflow_dispatch:
    inputs:
      scenario:
        description: Molecule scenario
        required: true
        type: choice
        options:
          - default
          - gbdbdir
          # - wuhcor1  # requires more than ~40GB of disk space

jobs:
  molecule:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: astral-sh/setup-uv@v10.1.0
        with:
          activate-environment: true

      - name: Install the required Python packages
        run: uv pip install -r requirements.txt -r molecule/requirements.txt

      - name: Install Vagrant and libvirt
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(. /etc/os-release && echo "$VERSION_CODENAME") main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install --yes libvirt-daemon-system libvirt-dev qemu-kvm vagrant

      - name: Enable and start the libvirt service, authorize access to KVM and libvirt socket
        run: |
          sudo systemctl enable --now libvirtd
          sudo chmod a+rw /dev/kvm /var/run/libvirt/libvirt-sock

      - name: Initialize Molecule libvirt storage pool
        run: |
          sudo virsh pool-define-as molecule dir --target /var/lib/libvirt/images
          sudo virsh pool-start molecule
          sudo virsh pool-autostart molecule

      - name: Install the libvirt Vagrant provider
        run: vagrant plugin install vagrant-libvirt

      - name: Install `community.vagrant` Ansible collection
        run: ansible-galaxy collection install community.vagrant

      - name: Run Ansible Molecule
        run: molecule --base-config molecule/base.yml test --scenario-name "${{ inputs.scenario }}"
