name: Ansible Molecule

on:
  workflow_dispatch:
    inputs:
      scenario:
        description: Molecule scenario
        required: true
        type: choice
        options:
          - default
          - gbdbdir
          # - wuhcor1  # requires more than ~40GB of disk space

jobs:
  molecule:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Setup Ansible Molecule
        uses: ./.github/actions/setup-molecule

      - name: Run Ansible Molecule
        run: molecule --base-config molecule/base.yml test --scenario-name "${{ inputs.scenario }}"
